<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tr gp490KMy git Samsung Inverter 9.5kg WA95CG4545BDSV (Model 2023)Samsung5.500.000-85.990.000Kt thc sau6 ngy Cn 7(4)5.500.000 5.990.000</name>
   <tag></tag>
   <elementGuidId>62d36420-9ab7-4f02-9176-f29936cffd39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.product-highlight-item.prod-item.lazy-prod-item._list_ico_9483._list_ico_10227</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='catalog-fs']/div[2]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>91fc6ba5-b130-48a9-a5b9-772c4c0218b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-highlight-item prod-item lazy-prod-item _list_ico_9483 _list_ico_10227</value>
      <webElementGuid>f7ffdb75-7914-44b8-b1b1-3e5b0fdd5416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cec499ed-1d96-4c80-8f29-c7aa5993f210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-chuyenmuc</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d0c9220-46bd-4bbe-9597-50055b77779e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>1f86253e-c47f-49b2-95f5-179d3500062f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>91ccf29d-a0b8-4673-a399-e87acb9e633e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>93479</value>
      <webElementGuid>61cbfc57-d641-428d-96f9-90a712d216a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trả góp490KMáy giặt Samsung Inverter 9.5kg WA95CG4545BDSV (Model 2023)Samsung5.500.000đ-8%5.990.000đKết thúc sau6 ngày Còn 7(4)5.500.000 đ5.990.000 đ</value>
      <webElementGuid>efe6cb0d-4721-4ef5-82d6-4a37da96d55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catalog-fs&quot;)/div[@class=&quot;cat-product-highlight&quot;]/div[@class=&quot;list-product-highlight spotlight-products&quot;]/ul[@class=&quot;product-highlight-wrap&quot;]/li[@class=&quot;product-highlight-item prod-item lazy-prod-item _list_ico_9483 _list_ico_10227&quot;]</value>
      <webElementGuid>2099abd1-710f-46b2-a3b8-6f0a87fd3e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catalog-fs']/div[2]/div/ul/li</value>
      <webElementGuid>a524589b-3086-43ab-a409-67a08a42d717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/ul/li</value>
      <webElementGuid>b1973563-1e21-4635-8d45-b8c407abd566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Trả góp490KMáy giặt Samsung Inverter 9.5kg WA95CG4545BDSV (Model 2023)Samsung5.500.000đ-8%5.990.000đKết thúc sau6 ngày Còn 7(4)5.500.000 đ5.990.000 đ' or . = 'Trả góp490KMáy giặt Samsung Inverter 9.5kg WA95CG4545BDSV (Model 2023)Samsung5.500.000đ-8%5.990.000đKết thúc sau6 ngày Còn 7(4)5.500.000 đ5.990.000 đ')]</value>
      <webElementGuid>cdf1bab3-20c1-4c52-84a0-54d53021e871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
