<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xa</name>
   <tag></tag>
   <elementGuidId>0206d687-ab1a-4fa7-991e-6c36c2bc0fdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.incart-prod-remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-place-holder']/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>017ae6b4-def6-476a-b880-a4ad92abbecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Xoá Robot hút bụi Ecovacs Deebot T10 khỏi giỏ hàng?</value>
      <webElementGuid>a88a6084-c8c5-4672-abff-420e24c1e93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>incart-prod-remove</value>
      <webElementGuid>91c61e28-31eb-4585-97c9-4d61807b40cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xóa</value>
      <webElementGuid>b936f15c-6c53-45d9-b6da-9f4af781fd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-place-holder&quot;)/div[@class=&quot;incart-container&quot;]/div[@class=&quot;incart-ls-prods&quot;]/div[@class=&quot;incart-prod-line&quot;]/div[@class=&quot;incart-prod-wrap&quot;]/div[@class=&quot;incart-price-wrap&quot;]/div[@class=&quot;incart-prod-qty-cont&quot;]/div[@class=&quot;incart-prod-check&quot;]/a[@class=&quot;incart-prod-remove&quot;]</value>
      <webElementGuid>7354a073-9ea5-4dc5-a2ed-13c2563a624a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-place-holder']/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>56de442f-dab2-4372-b438-1ae374ceb7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xóa')]</value>
      <webElementGuid>4a03c547-f94b-431f-bb16-c198901b9056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>62dbdfa3-892a-47e0-9c16-7a02c772b990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Xoá Robot hút bụi Ecovacs Deebot T10 khỏi giỏ hàng?' and (text() = ' Xóa' or . = ' Xóa')]</value>
      <webElementGuid>b6a15797-c8bf-4120-beb1-9e9af746789a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
