<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ly m khuyn mi_fa fa-shopping-cart</name>
   <tag></tag>
   <elementGuidId>04c2d5dd-04e9-4311-9964-b0f7def1c432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-shopping-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header-m']/div/div/div/div[2]/div[2]/a/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>364a17e4-069c-473a-8639-77fc0502487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-shopping-cart</value>
      <webElementGuid>9b25608e-11ec-4605-bf73-8106d76768ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f6e1083-cbc7-4b71-abbf-6348b364f25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-m&quot;)/div[@class=&quot;box-header&quot;]/div[@class=&quot;wrap&quot;]/div[@class=&quot;box-top-menu&quot;]/div[@class=&quot;block cart-and-account&quot;]/div[@class=&quot;cart-box&quot;]/a[@class=&quot;popup-cart-lnk&quot;]/div[@class=&quot;cart-link&quot;]/i[@class=&quot;fa fa-shopping-cart&quot;]</value>
      <webElementGuid>d0d16cf1-1ed7-4714-b278-463042cbce9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header-m']/div/div/div/div[2]/div[2]/a/div/i</value>
      <webElementGuid>c68ff979-315d-4794-82ca-90e010a44a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>b43971c6-cfe7-4888-bb8b-794698f079f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
