<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chn tt c_prod-chk</name>
   <tag></tag>
   <elementGuidId>78b1f8f8-f338-45a0-a21b-595361f9cc71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.incart-prod-check.checkbox > input.prod-chk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5b2e2f5-278d-4a60-8702-4c7f1aca2bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9f243839-1ac7-4356-9d66-b1cdd03edbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prod-chk</value>
      <webElementGuid>b5ece09b-50f8-4b19-a140-d088fea1e1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-place-holder&quot;)/div[@class=&quot;incart-container&quot;]/div[@class=&quot;incart-ls-prods&quot;]/div[@class=&quot;incart-prod-line&quot;]/div[@class=&quot;incart-prod-check checkbox&quot;]/input[@class=&quot;prod-chk&quot;]</value>
      <webElementGuid>a99cbced-8d45-4a57-8556-260e23672be5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>96857dd7-fd5f-4267-8698-6b13291634c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-place-holder']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>a3310aa7-79e1-4a4d-add9-36f88defff50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e2b8d508-7557-4f78-89dd-0ad095c02d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>256f37f3-6b64-4f92-bc36-f13d53570085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
