<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cho vo gi</name>
   <tag></tag>
   <elementGuidId>7e78a3c2-3960-4238-ae3a-120d08b96930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.title-pick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ba565d4-c38a-43f6-85f1-ad3cd0abfc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>d216349d-8c08-49c3-96e7-38660d95788a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-pick</value>
      <webElementGuid>40dc64be-bfb9-4068-8545-b2c464d7c218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho vào giỏ</value>
      <webElementGuid>ba777930-c99e-41a5-a742-bfb0f723a2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_pageBody_pnlProdOffer&quot;)/div[@class=&quot;view-detail-product&quot;]/div[@class=&quot;Product-info-right-top&quot;]/div[@class=&quot;Product-summary&quot;]/div[@class=&quot;pick-in-cart&quot;]/a[@class=&quot;title-pick&quot;]</value>
      <webElementGuid>5fe98dc2-c885-4bf1-bea6-d8c51794810b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[9]/a</value>
      <webElementGuid>bbb3a780-954c-40c3-87c8-93eae4b2ded8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cho vào giỏ')])[2]</value>
      <webElementGuid>481abb96-f8fa-467b-be8e-872cefae201b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>9ec2971f-ea18-4665-b050-e4feb8070c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div[3]/div/div[9]/a</value>
      <webElementGuid>404c11a1-e809-4743-9b63-98038e80daf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cho vào giỏ' or . = 'Cho vào giỏ')]</value>
      <webElementGuid>6f2cc06c-4f1f-4b58-9055-76ea31b564ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
