<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_thumb-list is-thumb</name>
   <tag></tag>
   <elementGuidId>17e1809e-64bf-4bef-b60e-e87fa04baa90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;p72198&quot;] > img.thumb-list.is-thumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='_products']/div/div/ul/li[3]/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ebffb58-d659-4472-b712-f497400f2850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sữa tắm thảo dược Nature Queen (100ml)</value>
      <webElementGuid>a07e67b0-49a7-4cd9-8b9c-b963fd42a7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s.meta.com.vn/img/thumb.ashx/200x200x95/Data/image/2020/10/16/sua-tam-thao-duoc-nature-queen-100ml-300.jpg</value>
      <webElementGuid>7274b590-9666-419b-b8e1-c7111600cea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://s.meta.com.vn/img/thumb.ashx/200x200x95/Data/image/2020/10/16/sua-tam-thao-duoc-nature-queen-100ml-300.jpg, https://s.meta.com.vn/img/thumb.ashx/300x300x95/Data/image/2020/10/16/sua-tam-thao-duoc-nature-queen-100ml-300.jpg 1.5x, https://s.meta.com.vn/img/thumb.ashx/400x400x95/Data/image/2020/10/16/sua-tam-thao-duoc-nature-queen-100ml-300.jpg 2x</value>
      <webElementGuid>e8ab7ae4-52ea-436e-be95-509855ac628e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>b569f7dc-5fde-4d9c-9f09-cb5a67f68bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>bf4c269a-a9ad-424f-8ab2-3f4b66183da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumb-list is-thumb</value>
      <webElementGuid>f9d7ea7e-a053-4d53-98a3-7c5e250c5c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_products&quot;)/div[@class=&quot;wrap-list-product-catagsub&quot;]/div[@class=&quot;list-product-highlight&quot;]/ul[@class=&quot;product-highlight-wrap&quot;]/li[@class=&quot;product-highlight-item prod-item lazy-prod-item loaded&quot;]/div[@class=&quot;lazy-holder&quot;]/div[@class=&quot;prod-hl-thumb&quot;]/a[1]/img[@class=&quot;thumb-list is-thumb&quot;]</value>
      <webElementGuid>b6a5835a-2b68-4a73-ae4b-10825ffc59bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='_products']/div/div/ul/li[3]/div/div[2]/a/img</value>
      <webElementGuid>499aeef4-4ccc-429b-a416-53d078a2b9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sữa tắm thảo dược Nature Queen (100ml)']</value>
      <webElementGuid>6f86aedf-8667-4686-8c44-8da2c28e78dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/a/img</value>
      <webElementGuid>55b78fab-d86e-40eb-80ab-69d4aef8c857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sữa tắm thảo dược Nature Queen (100ml)' and @src = 'https://s.meta.com.vn/img/thumb.ashx/200x200x95/Data/image/2020/10/16/sua-tam-thao-duoc-nature-queen-100ml-300.jpg']</value>
      <webElementGuid>97f75c4d-7a3d-4efc-bc62-185a0a57536d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
