<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cho vo gi</name>
   <tag></tag>
   <elementGuidId>f2d4f378-76dd-47f5-bc19-7f0d5f3fee1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.title-pick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e84b259b-6fe7-4a02-b7a7-6d41d634056f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>e311625b-e5a0-4090-a738-019b00e45bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-pick</value>
      <webElementGuid>f7cab486-674f-4003-a4ae-c7769fc57b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho vào giỏ</value>
      <webElementGuid>e9d03a95-f222-4642-81f9-9f4701de045c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_pageBody_pnlProdOffer&quot;)/div[@class=&quot;view-detail-product&quot;]/div[@class=&quot;Product-info-right-top&quot;]/div[@class=&quot;Product-summary&quot;]/div[@class=&quot;pick-in-cart&quot;]/a[@class=&quot;title-pick&quot;]</value>
      <webElementGuid>e941b3d7-d5e6-455f-9ec6-344514a3f97b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      <webElementGuid>12da2ed4-78ca-47f7-9001-49b65d28d79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cho vào giỏ')])[4]</value>
      <webElementGuid>511ad69b-203d-492f-bab2-46c554b6e042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>e32cbc01-3402-4d5c-a8fb-b3266326ea85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div[3]/div/div[7]/a</value>
      <webElementGuid>bf3a9944-49f5-451f-9e51-f05c63a536bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cho vào giỏ' or . = 'Cho vào giỏ')]</value>
      <webElementGuid>d233de73-c7a3-4c63-b9a0-928c0c926d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
