<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>38dcf4d4-ecdc-4fe3-b344-cf8f75b99d7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.color-item > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='attri-1']/span[2]/div/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>951eedd8-90f9-4f65-81f8-262f509242f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Data/Image/_Attrs/data-imay-nhao-bot-gourmetmaxx-sm-1504-green.jpg</value>
      <webElementGuid>601396ff-0a91-4ce8-b989-01dd7fce7f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attri-1&quot;)/span[@class=&quot;attri-vals info-spec-right&quot;]/div[@class=&quot;att-select att-layout-thumbnail&quot;]/ul[@class=&quot;option-thumb&quot;]/li[1]/a[@class=&quot;color-item&quot;]/img[1]</value>
      <webElementGuid>236402b9-6647-49ac-8556-2e17c1b97348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attri-1']/span[2]/div/ul/li/a/img</value>
      <webElementGuid>e8ea7f53-e235-4eec-8da9-69762722c33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li/a/img</value>
      <webElementGuid>0068d50a-e3e4-49ae-be5f-7e4faac1a33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Data/Image/_Attrs/data-imay-nhao-bot-gourmetmaxx-sm-1504-green.jpg']</value>
      <webElementGuid>34849d12-397c-4714-a4db-90cce7bb2611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
