<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cho vo gi</name>
   <tag></tag>
   <elementGuidId>3851d3e0-c495-4ffb-8d0d-be52d00bfd78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.title-pick</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7422a38-d52c-429e-bd4d-96f938a22117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>54619efa-e65e-4a9a-9ce7-5a4dd7b9bdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-pick</value>
      <webElementGuid>6422739b-9b50-4459-9a81-59e2c863b584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho vào giỏ</value>
      <webElementGuid>1e02c398-f7c9-41c7-85a8-a06ef7c71e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_pageBody_pnlProdOffer&quot;)/div[@class=&quot;view-detail-product&quot;]/div[@class=&quot;Product-info-right-top&quot;]/div[@class=&quot;Product-summary&quot;]/div[@class=&quot;pick-in-cart&quot;]/a[@class=&quot;title-pick&quot;]</value>
      <webElementGuid>b837f657-12f7-4ec6-8532-de47641ef61d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      <webElementGuid>e19a7d9b-73ae-4205-8442-c45e3d748467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cho vào giỏ')])[3]</value>
      <webElementGuid>f659eb69-3c1d-4d0a-b6d3-2315d5277484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[5]</value>
      <webElementGuid>6158a7a0-91ca-450d-9be9-2e33080073be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div[3]/div/div[7]/a</value>
      <webElementGuid>7f2de8db-98ba-43e5-a635-c62b65439d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cho vào giỏ' or . = 'Cho vào giỏ')]</value>
      <webElementGuid>df377230-6bd1-4a5f-b8f7-4d067e58fa8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
