<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gi n hng</name>
   <tag></tag>
   <elementGuidId>cf3c121a-4c56-44d4-9d49-9131eccc5474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnChkOut_first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnChkOut_first']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a977141-fc5c-4bc7-86f7-e206d3dcb7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-submit enable</value>
      <webElementGuid>aa372033-b93f-428f-927e-4f21af5e0656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnChkOut_first</value>
      <webElementGuid>4ffca1f8-8b6f-48c2-bd2d-5859e8538d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gửi đơn hàng</value>
      <webElementGuid>e342099a-fd15-4f7a-9499-194d0385e09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnChkOut_first&quot;)</value>
      <webElementGuid>cf1a5ef0-f9a6-42aa-b93a-aa7fb9920314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnChkOut_first']</value>
      <webElementGuid>7ac8200e-7ba0-4ef3-9366-2d544388c67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-info']/div/div/div[2]/div[2]/div[10]/div/a</value>
      <webElementGuid>2294770d-0986-40b7-b459-1a9c8fb652ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gửi đơn hàng')]</value>
      <webElementGuid>ae813809-f90e-4c8c-bc81-635431a46fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a</value>
      <webElementGuid>cf7abe75-6db7-4976-be14-52db4c38a260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnChkOut_first' and (text() = 'Gửi đơn hàng' or . = 'Gửi đơn hàng')]</value>
      <webElementGuid>85a137d6-8d16-496f-817e-f2e21c9a51e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
