<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng nhp bng email</name>
   <tag></tag>
   <elementGuidId>cfda9299-065d-45f6-a7c0-55297c5f4501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.login-type-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='center-m']/div[2]/div/div/div[2]/form/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb0328da-682a-42b1-ad81-2d227c9be7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-type-btn</value>
      <webElementGuid>770f2b46-a0a9-4906-84bc-9470e02d1ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Đăng nhập bằng email</value>
      <webElementGuid>1cdf0859-3141-4dc2-a948-7fdeb3fae6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;center-m&quot;)/div[@class=&quot;wrap&quot;]/div[@class=&quot;wrap-redux&quot;]/div[@class=&quot;member-row&quot;]/div[@class=&quot;member-col member-right&quot;]/form[1]/a[@class=&quot;login-type-btn&quot;]</value>
      <webElementGuid>5a466182-b0d6-4c9e-a10d-99c54595aebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='center-m']/div[2]/div/div/div[2]/form/a[2]</value>
      <webElementGuid>698ddcd0-238a-4725-bc50-b8d9b5893092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/a[2]</value>
      <webElementGuid>7d94dbd9-043f-4891-80fe-8b68c9a24968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Đăng nhập bằng email' or . = ' Đăng nhập bằng email')]</value>
      <webElementGuid>b4f3ea0d-29ee-45ac-9007-f34336d7eb2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
