<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Giao hng v thu tin ti nh (COD)</name>
   <tag></tag>
   <elementGuidId>5229ccfd-0cc3-4045-9b41-01e4244af54c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-name.empty-desc1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-choosen2']/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f22f13ab-58c0-42b8-8045-e8ab526984f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-name empty-desc1</value>
      <webElementGuid>941cd467-a9e1-477a-ba71-d88d20604cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giao hàng và thu tiền tại nhà (COD)</value>
      <webElementGuid>3960b2ae-3cd0-4508-b899-94a45c3af80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-choosen2&quot;)/div[@class=&quot;options&quot;]/div[1]/div[@class=&quot;item is-current&quot;]/div[@class=&quot;item-wrap&quot;]/div[@class=&quot;item-name empty-desc1&quot;]</value>
      <webElementGuid>22c8a33e-298d-4b2f-b384-53cb9cfd4987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-choosen2']/div[2]/div/div/div/div</value>
      <webElementGuid>5298cd5a-596c-4a75-b410-492794b04170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div</value>
      <webElementGuid>2555915e-8c7f-4647-8624-8b80de9e9187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Giao hàng và thu tiền tại nhà (COD)' or . = 'Giao hàng và thu tiền tại nhà (COD)')]</value>
      <webElementGuid>63d1dd52-35e3-499d-b73a-3e554eacf6b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
