<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2a8ef62f-189f-451d-bb3d-66220e22ea06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.bank-logo.bnpl-logo.online > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-choosen2']/div[2]/div/div[3]/div[2]/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>80fd6428-e4c0-4ecc-b25b-018c7c021fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Data/image/2022/12/09/onepay-logo.png</value>
      <webElementGuid>c3770dc9-26f2-4467-8e63-b0fe1ae6d2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-choosen2&quot;)/div[@class=&quot;options&quot;]/div[1]/div[@class=&quot;item is-current&quot;]/div[@class=&quot;bank-list bnpl online&quot;]/div[@class=&quot;bank-item bnpl online selected&quot;]/div[@class=&quot;bank-desc&quot;]/span[@class=&quot;bank-logo bnpl-logo online&quot;]/img[1]</value>
      <webElementGuid>58aecec2-cbf7-48ec-91c1-8a09fff90e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-choosen2']/div[2]/div/div[3]/div[2]/div/div/span/img</value>
      <webElementGuid>472bc713-06de-425a-a45c-59333bf369d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/img</value>
      <webElementGuid>e2e72410-3db4-45a2-a709-7d972d7de84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Data/image/2022/12/09/onepay-logo.png']</value>
      <webElementGuid>95b3c42c-0369-4188-b4d7-4828da294bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-choosen2']/div[2]/div/div[2]/div[2]/div[2]/div/span/img</value>
      <webElementGuid>348f9845-6bf1-45e1-8814-315a4355a499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/img</value>
      <webElementGuid>c22abd91-715c-47a1-bb65-012ae0f768e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/bank/tcb_bank.jpg']</value>
      <webElementGuid>7ca88e7a-45c1-4f59-930f-d626d4985001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
