<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_t_address</name>
   <tag></tag>
   <elementGuidId>86c32098-5206-42f9-83b9-4035d26792c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;t_address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='t_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98c4279a-31fb-4c1c-a7b9-874cb4c9a98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vat-input</value>
      <webElementGuid>cd5bc346-6210-4149-a24a-d9fc3f6461d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>533179e1-c232-4654-b235-9073ad7ff6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ đăng ký của công ty/tổ chức với cơ quan thuế</value>
      <webElementGuid>01da7a9a-f5d8-4368-913b-f236e744f2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>t_address</value>
      <webElementGuid>04ddef48-47fd-4b3d-986d-937b3cdbfeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2a79722e-575d-482b-9048-52bc0d0884e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-info&quot;)/div[@class=&quot;container wrap-checkout&quot;]/div[@class=&quot;checkout-inner&quot;]/div[@class=&quot;region cust-info&quot;]/div[@class=&quot;region-inner&quot;]/div[@class=&quot;row box-vat info&quot;]/div[@class=&quot;vat-row&quot;]/span[@class=&quot;right-block&quot;]/input[@class=&quot;vat-input&quot;]</value>
      <webElementGuid>2cbca7b3-9935-4f20-be76-a843b4c62563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='t_address']</value>
      <webElementGuid>c7cf1be7-1335-4308-9dd7-db1730912353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-info']/div/div/div[2]/div[2]/div[8]/div[3]/span[2]/input</value>
      <webElementGuid>71dd7810-8982-4270-8f14-cd356e32082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]/input</value>
      <webElementGuid>88cb5e2c-db6a-42f2-8b65-0e7b6010dc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Địa chỉ đăng ký của công ty/tổ chức với cơ quan thuế' and @name = 't_address']</value>
      <webElementGuid>5865dcff-cc89-485f-aa61-35931caac645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
