<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-input form-p actived</name>
   <tag></tag>
   <elementGuidId>9a51ffd2-ab3f-42d8-819f-ef99e4bb7507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-input.form-p.actived</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Phuong2112']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f0ce008-2bdd-4b40-a5c5-7d4c44cbf237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc621b1b-29a0-491c-bc45-b0f4b65520dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input form-p actived</value>
      <webElementGuid>9561f535-ef28-404c-9c1c-042e2fc69338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f84b6573-b7a1-4eb9-a83b-2ece0f652062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d07ff641-eee0-4426-9d2a-086d577e92dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a770e742-8b7e-4e47-a3eb-47d990df016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Phuong2112</value>
      <webElementGuid>87d32c55-7370-4be1-a66c-f8fd9c07b290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a5406845-5578-43c8-9848-3de86e9b88e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;center-m&quot;)/div[@class=&quot;wrap&quot;]/div[@class=&quot;wrap-redux&quot;]/div[@class=&quot;member-row&quot;]/div[@class=&quot;member-col member-right&quot;]/form[1]/div[@class=&quot;form-outline&quot;]/input[@class=&quot;form-input form-p actived&quot;]</value>
      <webElementGuid>5c0390e9-92a2-4058-bde7-5c2366b6d4e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Phuong2112']</value>
      <webElementGuid>a6031fd3-d9f2-404c-82be-c12ca82f880f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='center-m']/div[2]/div/div/div[2]/form/div[3]/input</value>
      <webElementGuid>6491cf63-0cbc-45a5-83a5-61bd8c89b257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>564d2d23-5b95-42c1-9493-c4b2dffd5cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5c7f15f4-4e16-41a4-9c57-fd327d958d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
