<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_t_code</name>
   <tag></tag>
   <elementGuidId>f4a2ee65-e734-4bd5-a2ba-4a93c51e51a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;t_code&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='t_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeff09f9-f29b-4338-aab5-f313ae6cc61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc5199b6-8e8d-4dbe-875d-acc26273ab82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vat-input</value>
      <webElementGuid>1c43e588-99e1-4f61-9df0-782a0072e24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập mã số thuế - nếu có</value>
      <webElementGuid>afc83c0d-2c2f-4055-be42-3bc05873b635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>t_code</value>
      <webElementGuid>f8b75636-c26b-44bc-be13-187454f928b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-info&quot;)/div[@class=&quot;container wrap-checkout&quot;]/div[@class=&quot;checkout-inner&quot;]/div[@class=&quot;region cust-info&quot;]/div[@class=&quot;region-inner&quot;]/div[@class=&quot;row box-vat info&quot;]/div[@class=&quot;vat-row&quot;]/span[@class=&quot;right-block&quot;]/input[@class=&quot;vat-input&quot;]</value>
      <webElementGuid>b261a9fe-0a08-442a-bc3c-7c3ad8292780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='t_code']</value>
      <webElementGuid>7b3f313c-e7c4-43b8-b3b4-96b72e71cce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-info']/div/div/div[2]/div[2]/div[8]/div/span[2]/input</value>
      <webElementGuid>e1b0bb52-72b3-4de6-9841-f476eb3a50d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>b2708db9-ecaf-4347-aa67-079d977ad974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nhập mã số thuế - nếu có' and @name = 't_code']</value>
      <webElementGuid>256cfb1b-e83d-4b56-9289-1f10c07b98f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
