<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_t_email</name>
   <tag></tag>
   <elementGuidId>6d2b5ed8-2041-4186-b7fb-001d70b83d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;t_email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='t_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7330596b-4c3c-4157-a336-8ddf92d227ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vat-input</value>
      <webElementGuid>baca9b54-3972-4ed2-9116-f3468fd91b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10647100-b4e8-4bfc-a60b-4f4ebaf4a17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập email để nhận hóa đơn điện tử do META gửi</value>
      <webElementGuid>c06b0fdc-d229-400e-bb63-7db52db34b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>t_email</value>
      <webElementGuid>9a78a9f1-7751-4bb5-949f-264c4e0f2c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-info&quot;)/div[@class=&quot;container wrap-checkout&quot;]/div[@class=&quot;checkout-inner&quot;]/div[@class=&quot;region cust-info&quot;]/div[@class=&quot;region-inner&quot;]/div[@class=&quot;row box-vat info&quot;]/div[@class=&quot;vat-row&quot;]/span[@class=&quot;right-block&quot;]/input[@class=&quot;vat-input&quot;]</value>
      <webElementGuid>41db2a0b-5217-4b6d-b9fb-190feb01caf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='t_email']</value>
      <webElementGuid>130960d4-2273-4eaa-9ec0-9b91b05d5a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-info']/div/div/div[2]/div[2]/div[8]/div[4]/span[2]/input</value>
      <webElementGuid>bcd6d2aa-b4f3-4f3f-887a-08f452a17361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span[2]/input</value>
      <webElementGuid>18155a7e-9a2f-4afa-9f31-614b60a399d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nhập email để nhận hóa đơn điện tử do META gửi' and @name = 't_email']</value>
      <webElementGuid>48a26003-aabd-4fa5-a0f4-38b6726d6791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
