<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>04ac9275-6865-48de-8fec-bbc74455c8c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBillingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBillingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a29a54bb-87b8-4161-b37d-7af4ad316d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-full-width bill-name</value>
      <webElementGuid>09efee11-7094-4205-9093-864c001fbef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e769a12a-1849-4e70-bad0-d1f8a548ce34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ và tên</value>
      <webElementGuid>66575121-c9df-4ac2-9d7e-3d02aa4ef29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBillingName</value>
      <webElementGuid>a07bbb45-3e10-4bab-a127-6f1a77a2321a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>17cb81f6-f509-4be2-a987-aa06876540b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c60ecc35-8052-4dd1-9f15-6a87c0115132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBillingName&quot;)</value>
      <webElementGuid>525cdf05-dcf9-4d4b-af78-95ed0acec2f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBillingName']</value>
      <webElementGuid>804eb184-86cc-4edb-bc18-10011aa1485a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-info']/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>f771a77c-276f-4ade-8bf6-e5f0650fe6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>97c47baa-bc3f-4919-8c05-14a4f6e4fdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Họ và tên' and @id = 'txtBillingName' and @name = 'name']</value>
      <webElementGuid>91d7c3af-56a6-49a8-b0e0-904fed5df069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
