<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chkvat</name>
   <tag></tag>
   <elementGuidId>c081d9eb-88fe-453d-b419-d00ce10d484e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chkvat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chkvat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52b895f6-cb49-49ac-9943-9dbc43978d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>73cec7fd-ee15-4b54-9e76-0f54130c7af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chkvat</value>
      <webElementGuid>f2e985ef-96b2-4feb-99a8-b18f03e20fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkvat</value>
      <webElementGuid>e9e28540-cdc1-4d67-844e-951f2addca22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Đánh dấu vào đây để nhập thông tin hóa đơn</value>
      <webElementGuid>4ec64432-b4fe-46ad-ad36-9971f1b400d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chkvat&quot;)</value>
      <webElementGuid>700d86b9-ed53-4ac3-90b4-1388cbead00a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chkvat']</value>
      <webElementGuid>2b134d13-bb03-4e6f-9993-8caa3f186f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-info']/div/div/div[2]/div[2]/div[7]/div/input</value>
      <webElementGuid>e87f918a-ca6f-42bb-ab87-cebb52ac687f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>53ef7372-777c-42dd-85f1-6063e2534799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chkvat' and @name = 'chkvat' and @title = 'Đánh dấu vào đây để nhập thông tin hóa đơn']</value>
      <webElementGuid>e8f307f3-5816-4c8c-bdfe-45231caed4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
