<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Nng</name>
   <tag></tag>
   <elementGuidId>067af12d-71bd-45d5-9b4e-6fb09639c5ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='addrEdit']/div/div/div/div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8da45cba-0497-4849-bceb-6d8460962fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li-item</value>
      <webElementGuid>794fc7b5-c401-418c-8b75-4b46a6318466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>183</value>
      <webElementGuid>b79e1eec-efab-4af6-b081-9737ae5c1345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đà Nẵng</value>
      <webElementGuid>31a7fad2-d1bc-4dd7-a67d-b9af112c7f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addrEdit&quot;)/div[@class=&quot;one-third column addr-item province-user&quot;]/div[@class=&quot;select large&quot;]/div[@class=&quot;list open&quot;]/div[@class=&quot;list-inner&quot;]/ul[@class=&quot;list-ul&quot;]/li[@class=&quot;li-item&quot;]</value>
      <webElementGuid>1bf21453-730a-48ae-bc0a-e1ddbe077b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addrEdit']/div/div/div/div/ul/li[3]</value>
      <webElementGuid>f12e1d63-2c4b-4e90-9d8c-3afbfcaaf66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]</value>
      <webElementGuid>f84c595a-b6bf-448b-870b-9a7e7369816f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Đà Nẵng' or . = 'Đà Nẵng')]</value>
      <webElementGuid>7c11dc90-de70-4f9f-961b-79c5eb5869ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
