<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbtnFindSearch</name>
   <tag></tag>
   <elementGuidId>7022c1a9-b017-49a9-8644-bf3b4c923c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnFindSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnFindSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1534a18-434a-4a8c-bd67-ce0dc9a43d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>64eb7f09-ac43-4c6e-b339-3d47b88641dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tìm kiếm</value>
      <webElementGuid>16d3565c-543a-4120-b02a-b84bdc787dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFindSearch</value>
      <webElementGuid>8bbe8017-ef72-4d07-b2d9-c18de7be94cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnFindSearch</value>
      <webElementGuid>6b4bf3e0-18a8-4e86-a6da-43b2aea3a5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFindSearch&quot;)</value>
      <webElementGuid>d7d7f4ed-695e-4e66-a376-f595e2fdad57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnFindSearch']</value>
      <webElementGuid>ee702a1a-a2f1-4372-96bc-a02b4b07db4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FindSubmit']/input</value>
      <webElementGuid>1b5c3e33-50cb-438a-8ea1-395ddf2d7a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7caa5177-4b72-4779-af42-7306a78f9a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnFindSearch']</value>
      <webElementGuid>fcfc1f0d-6f5f-4a56-9176-c5252cbd65fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
