<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_q</name>
   <tag></tag>
   <elementGuidId>0ad3f572-7d6e-4c4c-afcd-2004bf5b8b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtQuery</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtQuery']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77575e23-0feb-46a5-949e-14d476f4be67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6b82868-c6f0-473d-a17b-aa4aa3735caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>32cd4b11-9043-42a5-b24f-6767489a0fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3977db70-f2e5-4c7a-a13c-f6cc2209bff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtQuery</value>
      <webElementGuid>e454752a-47d8-4221-bab6-e1ba2b90d794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtQuery search-txt txtsearch has-mic ac_input</value>
      <webElementGuid>4012f801-cf0b-4d4a-85b9-2e24a2a169bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a68f3d8f-b022-499c-9e0a-6f4a538ae37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9af04e6f-8d28-4fbe-846b-acf69870992a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nhập từ khóa liên quan đến sản phẩm</value>
      <webElementGuid>5222360f-a773-45a7-ade8-96a958924d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn cần tìm kiếm sản phẩm gì?</value>
      <webElementGuid>593f87cc-37fe-4c6b-b5fd-c3ab41e03f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Nhập từ khóa liên quan đến sản phẩm')</value>
      <webElementGuid>ad34c551-7195-4fbb-9926-42e1b5fbd8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtQuery&quot;)</value>
      <webElementGuid>db14df5a-0735-41d8-b8a4-d6b45c20a6e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtQuery']</value>
      <webElementGuid>5d1c5aa0-3fc5-43fa-8561-f5bcbd7f0ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsearch']/input</value>
      <webElementGuid>f593825d-9cb3-4c98-8eae-75ed6499b6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8e6b828f-5dfd-4603-a301-2d999f0215b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'q' and @id = 'txtQuery' and @title = 'Nhập từ khóa liên quan đến sản phẩm' and @placeholder = 'Bạn cần tìm kiếm sản phẩm gì?']</value>
      <webElementGuid>91d31d9f-bc94-4686-a669-c678aae08ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
