<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Khng xa</name>
   <tag></tag>
   <elementGuidId>6cd96020-e18f-46a3-aefa-26225658dcbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='detail']/div[13]/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.swal-button.swal-button--cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ef877bd-5b3c-4109-ad30-f8773d00ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal-button swal-button--cancel</value>
      <webElementGuid>a5845ffb-ccc3-4bc5-9821-7eaf95319e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Không xóa</value>
      <webElementGuid>dbc3bb6f-ca1c-4425-8bda-e4a6d68c3d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail&quot;)/div[@class=&quot;swal-overlay swal-overlay--show-modal&quot;]/div[@class=&quot;swal-modal&quot;]/div[@class=&quot;swal-footer&quot;]/div[@class=&quot;swal-button-container&quot;]/button[@class=&quot;swal-button swal-button--cancel&quot;]</value>
      <webElementGuid>a500654d-f303-403a-91c4-416e9bb1c4b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='detail']/div[13]/div/div[2]/div/button</value>
      <webElementGuid>8f007174-f46e-4efc-b6b1-ff8ffd587b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/button</value>
      <webElementGuid>15e746ed-9783-4744-8e0e-e769b49945d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Không xóa' or . = 'Không xóa')]</value>
      <webElementGuid>83bf15ba-52fa-4ac1-a7ba-0349a496c73d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
