<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ng</name>
   <tag></tag>
   <elementGuidId>18aa0e14-ebf6-4c35-a4ae-c581179875a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-place-holder']/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.incart-header-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6da58488-485d-4cc5-b3ed-e57db4fe57ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>incart-header-close</value>
      <webElementGuid>617b04c1-d2a4-4ef5-ad86-b485addcfe47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>69130c3f-269f-48fb-abed-69ffa982dc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-place-holder&quot;)/div[@class=&quot;incart-header&quot;]/div[@class=&quot;incart-header-title&quot;]/a[1]/span[@class=&quot;incart-header-close&quot;]</value>
      <webElementGuid>7cb53ab9-eccf-48df-8a01-c1edbe62bef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-place-holder']/div/div/a/span</value>
      <webElementGuid>a68361d7-1f59-45d8-95ae-21e97b443780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>e6cbd1c8-1a5e-4202-a242-6ec371e2a2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Đóng' or . = 'Đóng')]</value>
      <webElementGuid>fcd69e92-472e-4131-9897-1ddf9353c90c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
