<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbtnFindSearch</name>
   <tag></tag>
   <elementGuidId>98e020a0-71b4-408f-a67d-757875a4313d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnFindSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnFindSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9dcb286-7e1a-426a-bda6-1fed8e8f83c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>14fa95ad-3b8b-4459-89f7-01c16a7b5b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tìm kiếm</value>
      <webElementGuid>e3562d81-9b6e-451a-981f-3bcffcc545f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFindSearch</value>
      <webElementGuid>58fc2e2a-4ba6-43c5-8166-dda3b94daf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnFindSearch</value>
      <webElementGuid>3c305ca4-c388-4ba8-99f9-8a06e509be0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFindSearch&quot;)</value>
      <webElementGuid>e338ce49-0131-4311-b116-4c4926e7bde3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnFindSearch']</value>
      <webElementGuid>d0f5bb16-6d1c-4019-9b68-6040274581a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FindSubmit']/input</value>
      <webElementGuid>62847ffb-e47a-445d-a58b-16c02e10dc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>135a83fa-8b52-4ac4-bece-0dd1a8a39f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnFindSearch']</value>
      <webElementGuid>4077a124-3e05-4c65-a8ff-2a1a05d6ba73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
