<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_q</name>
   <tag></tag>
   <elementGuidId>2db7c06f-c8c2-4424-b45c-9c9eca19dd64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtQuery</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtQuery']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78259e6e-7757-4b98-a506-931c2c740127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>817f89a4-2271-46ff-a468-5cade1cf38b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>ca873911-31b9-4339-918c-def647de8c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f19a0594-1e4e-4089-9400-d0d8aa518111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtQuery</value>
      <webElementGuid>625a9f2b-4192-40dd-afda-d9fbe0eb074b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtQuery search-txt txtsearch has-mic ac_input</value>
      <webElementGuid>34b63ce3-f797-442f-8f97-72a62fdf81d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af974f25-7f5f-42d0-bd72-fb89448c71cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>070e4d8e-3dcd-45bd-9da6-51f2508d8cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nhập từ khóa liên quan đến sản phẩm</value>
      <webElementGuid>518604d7-4ecf-4b68-bcfa-717498d9baaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn cần tìm kiếm sản phẩm gì?</value>
      <webElementGuid>5d1c9a49-bfeb-42af-bed3-5aa33f7b918b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Nhập từ khóa liên quan đến sản phẩm')</value>
      <webElementGuid>aa9e3b84-4c27-432f-b770-5ef1641ea2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtQuery&quot;)</value>
      <webElementGuid>b826bf9f-7716-437c-b710-9335e737c88c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtQuery']</value>
      <webElementGuid>eb994f55-80cf-4aed-a286-86e49ed22ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmsearch']/input</value>
      <webElementGuid>558035b2-eb59-4dcb-9fd3-489c37600b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>215abfe0-e9a3-4d1b-aded-dba3e3e81d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'q' and @id = 'txtQuery' and @title = 'Nhập từ khóa liên quan đến sản phẩm' and @placeholder = 'Bạn cần tìm kiếm sản phẩm gì?']</value>
      <webElementGuid>bc9e32bd-4ef9-43a6-a68d-a0d25c7bd98e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
