<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cho vo gi</name>
   <tag></tag>
   <elementGuidId>e7054486-0058-4cb5-add2-bc99a8140714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.title-pick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85396783-f812-4bec-89a3-0e887e6015b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>3d4baa6c-39e9-4f85-ab62-11a830cf4408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-pick</value>
      <webElementGuid>9a1b3049-d71f-4fd0-a690-227d28e0afdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho vào giỏ</value>
      <webElementGuid>94cc795d-5f27-4762-b445-d479296b7810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_pageBody_pnlProdOffer&quot;)/div[@class=&quot;view-detail-product&quot;]/div[@class=&quot;Product-info-right-top&quot;]/div[@class=&quot;Product-summary&quot;]/div[@class=&quot;pick-in-cart&quot;]/a[@class=&quot;title-pick&quot;]</value>
      <webElementGuid>1619f341-46a9-437e-9970-b34635d7fb76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      <webElementGuid>6a22b175-8d1e-43e4-88d1-ad02b890d2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cho vào giỏ')])[2]</value>
      <webElementGuid>d6163cbb-1863-4d4e-907c-d6526442c8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>9a2832cb-82a2-4aae-aec8-6961965253ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div[3]/div/div[7]/a</value>
      <webElementGuid>6a4fcb2f-590c-441e-af3c-a324076938c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cho vào giỏ' or . = 'Cho vào giỏ')]</value>
      <webElementGuid>434a44c8-9f51-406b-aa09-07fe29e4532f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
