<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xa</name>
   <tag></tag>
   <elementGuidId>8331d7cd-be4d-42c1-a63a-959a6728da6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.swal-button.swal-button--remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='detail']/div[13]/div/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12db32a0-8dac-41a5-9211-2eb3b233bdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal-button swal-button--remove</value>
      <webElementGuid>947f9a5a-6878-4303-bb9a-012921dfa28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa</value>
      <webElementGuid>1b7b4f2a-d404-429c-ad68-8a3b443bab6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail&quot;)/div[@class=&quot;swal-overlay swal-overlay--show-modal&quot;]/div[@class=&quot;swal-modal&quot;]/div[@class=&quot;swal-footer&quot;]/div[@class=&quot;swal-button-container&quot;]/button[@class=&quot;swal-button swal-button--remove&quot;]</value>
      <webElementGuid>4780a5a9-bb19-4064-a3e7-3d44b276c651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='detail']/div[13]/div/div[2]/div[2]/button</value>
      <webElementGuid>e3bb0ade-bac4-4f85-a36b-5dc2b96a2363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div[2]/button</value>
      <webElementGuid>153b1476-45f4-4ff9-a1e1-f3a41d79630b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Xóa' or . = 'Xóa')]</value>
      <webElementGuid>fafbb7de-21ff-4fcb-8d00-98070175890e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
