<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ng</name>
   <tag></tag>
   <elementGuidId>5a599d91-58bb-47f5-adcc-8febdeee3cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.incart-header-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-place-holder']/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>297502db-5659-4788-9a78-a65440bdccfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>incart-header-close</value>
      <webElementGuid>1fdd572c-4079-4b57-824b-14013467e0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>e222e70d-222e-407f-b2ed-c20f0f3ffc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-place-holder&quot;)/div[@class=&quot;incart-header&quot;]/div[@class=&quot;incart-header-title&quot;]/a[1]/span[@class=&quot;incart-header-close&quot;]</value>
      <webElementGuid>cc25f6df-bc4b-4e01-96c5-78976ce90c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-place-holder']/div/div/a/span</value>
      <webElementGuid>8f03e079-5112-4c50-8960-73a9eb27b576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>e8ec9868-2d85-4012-8ce8-46c17376998a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Đóng' or . = 'Đóng')]</value>
      <webElementGuid>c1b25165-0253-46ea-9476-12d5523d3044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
