<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cho vo gi</name>
   <tag></tag>
   <elementGuidId>04820b45-7a68-40be-b569-2e4060bf7caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.title-pick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29f779f0-6183-4467-813d-49f3a1b0d70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>6a286f49-ad68-407c-95d6-4f9d9ad84f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-pick</value>
      <webElementGuid>36fac35b-8001-4c1e-96f5-370919c521a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho vào giỏ</value>
      <webElementGuid>aa102165-2eda-4892-9118-60039d812b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_pageBody_pnlProdOffer&quot;)/div[@class=&quot;view-detail-product&quot;]/div[@class=&quot;Product-info-right-top&quot;]/div[@class=&quot;Product-summary&quot;]/div[@class=&quot;pick-in-cart&quot;]/a[@class=&quot;title-pick&quot;]</value>
      <webElementGuid>7fa41025-e2fa-494e-afcb-a48ab6065500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_pageBody_pnlProdOffer']/div/div[3]/div/div[7]/a</value>
      <webElementGuid>0f16920f-2e5d-41e6-82a8-26885823f3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cho vào giỏ')])[4]</value>
      <webElementGuid>3835df70-f9e5-4979-a908-832bd8da403d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>a52f0dd5-c285-4233-a803-46278e0f2c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div[3]/div/div[7]/a</value>
      <webElementGuid>1c7b0dba-0497-44c0-b3c7-e9215d7e71be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cho vào giỏ' or . = 'Cho vào giỏ')]</value>
      <webElementGuid>8033863a-9b29-44d6-b4f6-527d41c58262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
