<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1c59b4cc-3d16-40fc-a518-b8020807c8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.close-popup > span > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prod-attr-zone-holder']/div/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>125e2e3f-a28c-46ee-a692-b5548fb73935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/close-popup.svg</value>
      <webElementGuid>3cd55203-e41c-47aa-becb-08cc8486c2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prod-attr-zone-holder&quot;)/div[@class=&quot;prod-attr-zone-wrap&quot;]/div[@class=&quot;prod-img-price-zone&quot;]/div[@class=&quot;close-popup&quot;]/span[1]/img[1]</value>
      <webElementGuid>1750e0eb-22ed-4015-b328-a810f807f8a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prod-attr-zone-holder']/div/div/div/span/img</value>
      <webElementGuid>8a67ac7d-8a8b-412e-b4ba-384d217140fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/img</value>
      <webElementGuid>fea26776-652a-48ba-b7a0-a309b784f04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/close-popup.svg']</value>
      <webElementGuid>d3e66716-203b-4b57-a3c4-828ee9e546e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
